name: Deploy to Virtual Machine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: faralpha-assessment
      
      - name: Install dependencies
        run: npm install
        working-directory: faralpha-assessment/backend

      - name: Deploy to virtual machine
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd backend && \
            git pull origin main || exit 1 && \
            npm install || exit 1 && \
            node server.js || exit 1'
